query Animes(
  $genres: [String!]
  $studios: [String!]
  $years: [Int!]
  $translations: [Int!]
  $search: String
  $season: AnimeSeason
  $status: AnimeStatus
  $type: AnimeType
  $ratingMpa: RatingMpa
  $minimalAge: Int
  $order: AnimeOrder
  $sort: SortOrder
  $page: Int = 0
  $limit: Int = 30
) {
  animes(
    genres: $genres
    studios: $studios
    years: $years
    translations: $translations
    search: $search
    season: $season
    status: $status
    type: $type
    ratingMpa: $ratingMpa
    minimalAge: $minimalAge
    order: $order
    sort: $sort
    page: $page
    limit: $limit
  ) {
    data {
      id
      url
      title
      image {
        large
        medium
      }
      type
      status
      rating
      year
      season
      episodesCount
      episodesAired
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      page
      totalPages
      totalCount
      limit
    }
  }
}